# Site settings
title: Burgerraad
email: info@burgerraad.be
description: > # this means to ignore newlines until "baseurl:"
  Dit is de website van de Burgerraad, een experiment
  in conflictvrije politiek en burgerinspraak.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.burgerraad.be" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
